import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-around',
    alignItems: 'center',
    marginTop: 15,
  },
  modalContainer: {
    flex: 1,
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  settingsContainer: {
    flex: 1,
    flexWrap: 'wrap',
    maxHeight: 400,
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingLeft: 200,
  },
  bigButton: {
    width: 400,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    backgroundColor: '#83A3C2',
    margin: 11,
    shadowOpacity: 0.8,
    elevation: 8,
    shadowColor: 'black',
    shadowOffset: {width: 2, height: -4},
    shadowRadius: 3,
  },
  bigName: {
    fontSize: 43,
    textAlign: 'center',
    color: '#EAEAEA',
  },
  heading: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 13,
  },
  header: {
    fontSize: 30,
    color: '#222222',
    paddingBottom: 15,
    backgroundColor: '#',
  },
  image: {
    flex: 1,
    justifyContent: 'center',
  },
  shadowProp: {
    shadowColor: 'black',
    shadowOffset: {width: 2, height: -4},
    shadowOpacity: 2,
    shadowRadius: 3,
  },
  elevation: {
    elevation: 20,
    shadowColor: 'black',
  },
  buttonHover: {
    marginTop: 10,
    borderRadius: 25,
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 50,
    paddingRight: 50,
    shadowColor: 'rgba(46, 229, 157, 0.4)',
    shadowOpacity: 1.5,
    elevation: 8,
    shadowRadius: 20,
    shadowOffset: {width: 1, height: 13},
    backgroundColor: '#2EE59D',
    color: '#FFFFFF',
  },
  activeButton: {
    width: 225,
    height: 95,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    backgroundColor: '#83A3C2',
    margin: 10,
    padding: 1,
    shadowOpacity: 0.8,
    elevation: 8,
    shadowColor: 'black',
    shadowOffset: {width: 2, height: -4},
    shadowRadius: 3,
  },
  notActiveButton: {
    width: 225,
    height: 95,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    margin: 11,
    shadowOpacity: 0.8,
    elevation: 8,
    shadowColor: 'black',
    shadowOffset: {width: 2, height: -4},
    shadowRadius: 3,
    backgroundColor: '#fff',
  },
  childName: {
    fontSize: 35,
    textAlign: 'center',
    color: '#EAEAEA',
  },
  bigButtonFormik: {
    width: 1000,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 30,
    backgroundColor: '#83A3C2',
    margin: 11,
    shadowOpacity: 0.8,
    elevation: 8,
    shadowColor: 'black',
    shadowOffset: {width: 2, height: -4},
    shadowRadius: 3,
  },
  input: {
    width: 1000,
    height: 75,
    borderWidth: 1,
    borderColor: 'black',
    padding: 10,
    paddingRight: 20,
    borderRadius: 26,
    fontSize: 26,
    margin: 7,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalView: {
    width: 1240,
    height: 650,
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalButton: {
    borderRadius: 20,
    padding: 10,
    fontSize: 45,
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  buttonOpen: {
    // backgroundColor: '#F194FF',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 25,
  },
  modalText: {
    marginBottom: 5,
    textAlign: 'center',
  },
});
