export const strings = {
  addChild: 'הוספת ילד',
  editChild: 'עריכת ילד',
  removeChild: 'הסרת ילד',
  addGroup: 'הוספת קבוצה',
  editGroup: 'עריכת קבוצה',
  removeGroup: 'הסרת קבוצה',
  childAddedSeccesfully: 'הילד נוסף בהצלחה',
  groupAddedSeccesfully: 'הקבוצה נוספה בהצלחה',
  childEditedSeccesfully: 'הילד עודכן בהצלחה',
  ok: 'אישור',
  cancel: 'ביטול',
  firstName: 'שם פרטי',
  lastName: 'שם משפחה',
  address: 'כתובת',
  parentPhone: 'טלפון הורה 1',
  parent2Phone: 'טלפון הורה 2',
  childrenGroups: 'כל הקבוצות',
  settings: 'הגדרות',
  logout: 'התנתק',
  chooseChildToRemove: 'בחר ילד להסרה',
  chooseChildToEdit: 'בחר ילד לעריכה',
  chooseChild: 'בחר ילד לסימון הגעתו לגן',
  chooseGroupToRemove: 'בחר קבוצה להסרה',
  allChildrenList: 'רשימת כל הילדים',
  groupName: 'שם הקבוצה:',
  assistantName: 'שם הסייעת:',
  windowNotClosed: 'החלון טרם נסגר',
  noGroupToShow: 'אין קבוצות',
  noChildrenToShow: 'אין ילדים בקבוצה',
  sureYouWantToRemove: 'האם ברצונך למחוק?',
  chooseGroupToEdit: 'בחר קבוצה לעריכה',
  chooseGroup: 'בחר קבוצה',
  tooShortName: 'שם פרטי חייב להכיל לפחות 2 תווים',
  tooShortLastName: 'שם משפחה חייב להכיל לפחות 2 תווים',
  tooLongName: 'שם פרטי יכול להכיל עד 15 תווים',
  tooLongLastName: 'שם פרטי יכול להכיל עד 15 תווים',
  insertFirstName: 'יש להכניס שם פרטי',
  insertLastName: 'יש להכניס שם משפחה',
  validationPhone: 'יש להכניס מספר טלפון נייד תקין',
  phoneMissing: 'יש להכניס מספר טלפון נייד אחד לפחות',
  groupMissing: 'יש לבחור קבוצה',
  noGroups: 'אין קבוצות, לחץ על מנת להוסיף',
  popUpDeleteGroupWarning:
    'שימו לב שבעת מחיקת הקבוצה ימחקו כל הילדים המשוייכים אליה. ולדאוג שכל הילדים ישוייכו מבעוד מועד לקבוצה אחרת',
};

export const screenNames = {
  register: 'REGISTER',
  login: 'LOGIN',
  groups: 'GROUPS',
  allChildrenList: 'ALL_CHILDREN_LIST',
  settings: 'SETTINGS',
  removeChild: 'REMOVE_CHILD',
  addChild: 'ADD_CHILD',
  editChild: 'EDIT_CHILD',
  addGroup: 'ADD_GROUP',
  childrenListForEdit: 'CHILDREN_LIST_FOR_EDIT',
  editGroup: 'EDIT_GROUP',
  removeGroup: 'REMOVE_GROUP',
  groupListForEdit: 'GROUP_LIST_FOR_EDIT',
};

export const formikValues = {
  firstName: 'firstName',
  lastName: 'lastName',
  address: 'address',
  parentPhone: 'parentPhone',
  parent2Phone: 'parent2Phone',
  groupName: 'groupName',
  assistantName: 'assistantName',
  group: 'group',
};
