export const strings = {
  welcome: 'ברוכים הבאים',
  enter: 'כניסה',
  login: 'התחבר',
  logout: 'התנתק',
  registerToSystem: 'הרשמה למערכת',
  login: 'התחברות',
  register: 'הרשמה',
  addChild: 'הוספת ילד',
  editChild: 'עריכת ילד',
  removeChild: 'הסרת ילד',
  addGroup: 'הוספת קבוצה',
  editGroup: 'עריכת קבוצה',
  removeGroup: 'הסרת קבוצה',
  childAddedSeccesfully: 'הילד נוסף בהצלחה',
  userAddedSeccesfully: 'הגן נוסף בהצלחה',
  groupAddedSeccesfully: 'הקבוצה נוספה בהצלחה',
  childEditedSeccesfully: 'הילד עודכן בהצלחה',
  ok: 'אישור',
  cancel: 'ביטול',
  firstName: 'שם פרטי',
  lastName: 'שם משפחה',
  address: 'כתובת',
  parentPhone: 'טלפון הורה',
  parent2Phone: 'טלפון הורה נוסף',
  childrenGroups: 'כל הקבוצות',
  settings: 'הגדרות',
  logout: 'התנתק',
  chooseChildToRemove: 'בחר ילד להסרה',
  chooseChildToEdit: 'בחר ילד לעריכה',
  chooseChild: 'בחר ילד לסימון הגעתו לגן',
  chooseGroupToRemove: 'בחר קבוצה להסרה',
  allChildrenList: 'רשימת כל הילדים',
  groupName: 'שם הקבוצה:',
  assistantName: 'שם הסייעת:',
  windowNotClosed: 'החלון טרם נסגר',
  noGroupToShow: 'אין קבוצות',
  noChildrenToShow: 'אין ילדים בקבוצה',
  sureYouWantToRemove: 'האם ברצונך למחוק?',
  chooseGroupToEdit: 'בחר קבוצה לעריכה',
  chooseGroup: 'בחר קבוצה',
  tooShortName: 'שם פרטי חייב להכיל לפחות 2 תווים',
  tooShortLastName: 'שם משפחה חייב להכיל לפחות 2 תווים',
  tooLongName: 'שם פרטי יכול להכיל עד 15 תווים',
  tooLongLastName: 'שם פרטי יכול להכיל עד 15 תווים',
  insertFirstName: 'יש להכניס שם פרטי',
  insertLastName: 'יש להכניס שם משפחה',
  tooShortGroupName: 'שם קבוצה חייב להכיל לפחות 2 תווים',
  tooLongGroupName: 'שם קבוצה יכול להכיל עד 15 תווים',
  insertGroupName: 'יש להכניס שם קבוצה',
  validationPhone: 'יש להכניס מספר טלפון נייד תקין',
  phoneMissing: 'יש להכניס מספר טלפון נייד',
  groupMissing: 'יש לבחור קבוצה',
  noGroups: 'אין קבוצות, לחץ על מנת להוסיף',
  popUpDeleteGroupWarning:
    'שימו לב! בעת מחיקת הקבוצה ימחקו כל הילדים המשוייכים אליה. יש לדאוג שכל הילדים ישוייכו מבעוד מועד לקבוצה אחרת',
  arrived: 'הגיע/ה',
  groupUpdatedSeccesfully: 'הקבוצה עודכנה בהצלחה',
  groupUserUpdatedSeccesfully: 'הגן עודכנה בהצלחה',
  noPasswordEntered: 'יש להכניס סיסמה',
  userName: 'שם הגן/הגננת',
  password: 'סיסמה',
  phoneNumber: 'טלפון',
  email: 'כתובת דוא"ל',
  addUser: 'הוספת גן',
};

export const screenNames = {
  homeScreen: 'HOME_SCREEN',
  register: 'REGISTER',
  login: 'LOGIN',
  groups: 'GROUPS',
  allChildrenList: 'ALL_CHILDREN_LIST',
  settings: 'SETTINGS',
  removeChild: 'REMOVE_CHILD',
  addChild: 'ADD_CHILD',
  editChild: 'EDIT_CHILD',
  addGroup: 'ADD_GROUP',
  childrenListForEdit: 'CHILDREN_LIST_FOR_EDIT',
  editGroup: 'EDIT_GROUP',
  removeGroup: 'REMOVE_GROUP',
  groupListForEdit: 'GROUP_LIST_FOR_EDIT',
};

export const formikValues = {
  firstName: 'firstName',
  lastName: 'lastName',
  address: 'address',
  parentPhone: 'parentPhone',
  parent2Phone: 'parent2Phone',
  groupName: 'groupName',
  assistantName: 'assistantName',
  group: 'group',
  userName: 'userName',
  password: 'password',
  email: 'email',
  phoneNumber: 'phoneNumber',
};
